travis:
  secure:
    BINSTAR_TOKEN: gkzRmxmQ7hzjFKtS8qnFCS3IycwbsExPpeNsgyc9ni+ADAczHcsaX3Y0hj4L6NgAK12BtKaJjzotGSDvngOy4TyRjcW2ONXK0BouF3w7fda+Skav5RBv5Nq8jQiTdhcsnUSINTTIeu9zofzzgeKRNp71M0Y2ygKKE+wbJr4jZW+mkOxytu1LcNx2WLt8P453seu/LOxXMjxIvJdKqdlc7YpyIhy7bjAbUKAOxOP6M5DOAY+n3MXxTzM7m79j/DoEph8atY+doVzIUFjjEP73l1Ir/aM9YzZQwFCZoL/y7G6ajHQKioiPcK9ilrJlaRWFh2Cuj+EI+PdFYoxErqA1pwqrRSVHo1bhMk5WxrJCbqgigEvKEbowluKGNKRR5+Zd+SG+5a9gw0EylqHUM4r3XbBdMqxhEWkqrnSoqj9nIsm3lOfaC3crDs1x/jckIXn5SaFeqeTz9E1uS3SkWVWljpMYFhmjH44abpjCmzIg3hBlbz40NhcKJmTrMKxh0s3AiKxDrlvUKzBHOxC0QSMbcC8UKl4H1DEmBXSDn37eWibFONqHQ2lkhHzTX0zsAQMVHrEu/QSECTYINIPM9e1v1PVL9E2FD94zL+4WcobS6pPb9AzC1upASQEnnRwBVdiKyxjNH92Mq/tO8ryBWxwKYstjkK55WnWnhIMM83Aocjc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
